name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: "8"

      - name: Build
        run: mvn clean package -DskipTests

      - name: Upload to Releases
        uses: softprops/action-gh-release@v1
        with:
          files: target/jmx-spec-1.0.jar